# ColorCodes Format Assist by Maxipad_ (TheOfficialMaxipad)
# Version 2.0 Release
# Reload Permission -> color.reload

Reload Message: '&8[&aColorCodes&8] &7has been successfully reloaded! (v1.0)'
Line1: '&8&l&m<---------&8[&6ColorCodes&8]&8&l&m--------->'
Line2: '&00 &11 &22 &33 &44 &55 &66 &77 &88 &99 &aa &bb &cc &dd &ee &ff'
Line3: '&mm Strikethrough&r &nn Underline&r &ll Bold'
Line4: '& k &kMagic&r & o &oItalic'
Line5: '&8&l&m<---------------------------->'